version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always
    networks:
      - monitoramento-network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - monitoramento-network
  app:
    build: .
    container_name: sensor-api
    depends_on:
      - elasticsearch
      - mosquitto
    ports:
      - "8080:8080"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - FASTAPI_URL=http://host.docker.internal:8000/sensor/analisar-fluxo
      - SPRING_MQTT_URL=tcp://mosquitto:1883
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoramento-network



  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - monitoramento-network

volumes:
  es_data:

networks:
  monitoramento-network:
    driver: bridge